module.exports = {
    COMMUNITY_CHAT: "COMMUNITY CHAT",
    USER_CONNECTED: "USER CONNECTED",
    USER_DISCONNECTED: "USER DISCONNECTED",
    MESSAGE_RECEIVED: "MESSAGE RECEIVED",
    MESSAGE_SENT: "MESSAGE SENT",
    TYPING: "TYPING",
    VERIFY_USER: "VERIFY USER",
    LOGOUT: "LOGOUT",
    
}